apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: kindlb
  namespace: metallb-system
spec:
  addresses:
  - 172.29.255.200-172.29.255.210
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: empty
  namespace: metallb-system
