apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sample
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://ingress-nginx-controller.ingress-nginx.svc.cluster.local/gitea/gitea/apps.git
    targetRevision: HEAD
    path: sample
  destination:
    server: https://kubernetes.default.svc
    namespace: sample
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
